# Generated by Django 6.0.5 on 2026-05-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.URLField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('bando', models.CharField(max_length=50)),
                ('grado_rango', models.CharField(max_length=50)),
                ('energia_maldita', models.IntegerField()),
                ('posee_expansion_dominio', models.BooleanField(default=False)),
            ],
        ),
    ]
